# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: music.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmusic.proto\"\x07\n\x05\x45mpty\" \n\x0bSongRequest\x12\x11\n\tsong_name\x18\x01 \x01(\t\"b\n\x0cSongResponse\x12\x11\n\tsong_name\x18\x01 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x02 \x01(\t\x12\r\n\x05\x61lbum\x18\x03 \x01(\t\x12\x13\n\x0b\x61lbum_image\x18\x04 \x01(\t\x12\x0b\n\x03url\x18\x05 \x01(\t\"@\n\x05\x41lbum\x12\x12\n\nalbum_name\x18\x01 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x02 \x01(\t\x12\x13\n\x0b\x61lbum_image\x18\x03 \x01(\t\"#\n\tAlbumList\x12\x16\n\x06\x61lbums\x18\x01 \x03(\x0b\x32\x06.Album2_\n\x0cMusicService\x12&\n\x07GetSong\x12\x0c.SongRequest\x1a\r.SongResponse\x12\'\n\x11GetFeaturedAlbums\x12\x06.Empty\x1a\n.AlbumListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'music_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=15
  _globals['_EMPTY']._serialized_end=22
  _globals['_SONGREQUEST']._serialized_start=24
  _globals['_SONGREQUEST']._serialized_end=56
  _globals['_SONGRESPONSE']._serialized_start=58
  _globals['_SONGRESPONSE']._serialized_end=156
  _globals['_ALBUM']._serialized_start=158
  _globals['_ALBUM']._serialized_end=222
  _globals['_ALBUMLIST']._serialized_start=224
  _globals['_ALBUMLIST']._serialized_end=259
  _globals['_MUSICSERVICE']._serialized_start=261
  _globals['_MUSICSERVICE']._serialized_end=356
# @@protoc_insertion_point(module_scope)
