# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: music.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmusic.proto\" \n\x0bSongRequest\x12\x11\n\tsong_name\x18\x01 \x01(\t\"b\n\x0cSongResponse\x12\x11\n\tsong_name\x18\x01 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x02 \x01(\t\x12\r\n\x05\x61lbum\x18\x03 \x01(\t\x12\x13\n\x0b\x61lbum_image\x18\x04 \x01(\t\x12\x0b\n\x03url\x18\x05 \x01(\t26\n\x0cMusicService\x12&\n\x07GetSong\x12\x0c.SongRequest\x1a\r.SongResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'music_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SONGREQUEST']._serialized_start=15
  _globals['_SONGREQUEST']._serialized_end=47
  _globals['_SONGRESPONSE']._serialized_start=49
  _globals['_SONGRESPONSE']._serialized_end=147
  _globals['_MUSICSERVICE']._serialized_start=149
  _globals['_MUSICSERVICE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
