# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: music.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmusic.proto\x12\x05music\" \n\x0bSongRequest\x12\x11\n\tsong_name\x18\x01 \x01(\t\"M\n\x0cSongResponse\x12\x11\n\tsong_name\x18\x01 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x02 \x01(\t\x12\r\n\x05\x61lbum\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t2B\n\x0cMusicService\x12\x32\n\x07GetSong\x12\x12.music.SongRequest\x1a\x13.music.SongResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'music_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SONGREQUEST']._serialized_start=22
  _globals['_SONGREQUEST']._serialized_end=54
  _globals['_SONGRESPONSE']._serialized_start=56
  _globals['_SONGRESPONSE']._serialized_end=133
  _globals['_MUSICSERVICE']._serialized_start=135
  _globals['_MUSICSERVICE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
